apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: production
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore

  target:
    name: app-secrets
    creationPolicy: Owner

  data:
    - secretKey: DB_HOST
      remoteRef:
        key: allsecrets
        property: DB_HOST
    
    - secretKey: DB_USERNAME
      remoteRef:
        key: allsecrets
        property: DB_USERNAME

    - secretKey: DB_PASSWORD
      remoteRef:
        key: allsecrets
        property: DB_PASSWORD

    - secretKey: REDIS_AUTH
      remoteRef:
        key: allsecrets
        property: REDIS_AUTH
