# Prod Profile Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-service:3306/user_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rootpassword}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# JWT Settings (At least 256 bits key for HS256)
demo.app.jwtSecret=${JWT_SECRET:9a6747fc6259aa374ab4e1bb03074b6ec7f1e812fbb5e5a9cc9f36551b9e28f3}
demo.app.jwtExpirationMs=${JWT_EXPIRATION_MS:86400000}
