spring.application.name=demo
spring.profiles.active=dev

server.servlet.context-path=/api

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

order.service.url=${ORDER_SERVICE_URL:http://backend-order}