spring.application.name=order-service

server.port=8080
server.servlet.context-path=/api/orders

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-service:3306/order_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rootpassword}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
